### ISSUE TITLE
Wrong inittype on CentOS 6

### ISSUE THREAD

**Issue by tuxmaster** [hfm/puppet-initsystem#2]
The facter module will report upstart for CentOS6.
But with this, the puppet function service will fail.
sample:
service { 'foo':
  provider => $::initsystem
 ..
}
will fails with:
change from false to true failed: Command update_rc is missing
because the right type will be redhat instant of upstart here.

**Comment by hfm** [comment]
This module will not support provider attributes for service type. Your issue is not bug of this module.
